routes/web.php
<?php

Route::get('doi_ngon_ngu/{ngon_ngu}',function($ngon_ngu){
	Session::put('ngon_ngu',$ngon_ngu);
});

Route::get('test','Controller@test');


Route::get('','LoginController@view_login')->name('view_login');
Route::post('process_login','LoginController@process_login')->name('process_login');

Route::group(['middleware' => 'CheckLogin'],function(){
	Route::get('welcome','Controller@welcome')->name('welcome');

	Route::get('form','SinhVienController@form');
	Route::get('ajax','SinhVienController@ajax')->name('ajax');

	Route::group(['as' => 'dau_nam.', 'prefix' => 'dau_nam'],function(){
		Route::group(['as' => 'sinh_vien.', 'prefix' => 'sinh_vien'],function(){
			Route::get('choose_by_lop','SinhVienController@choose_by_lop')->name('choose_by_lop');
			Route::get('view_by_lop','SinhVienController@view_by_lop')->name('view_by_lop');

			// đổi ảnh
			Route::get('view_change_anh/{ma}','SinhVienController@view_change_anh')->name('view_change_anh');
			Route::post('process_change_anh/{ma}','SinhVienController@process_change_anh')->name('process_change_anh');

			// làm việc với file excel
			Route::get('view_insert_with_excel','SinhVienController@view_insert_with_excel')->name('view_insert_with_excel');
			Route::post('process_insert_with_excel','SinhVienController@process_insert_with_excel')->name('process_insert_with_excel');

			Route::get('export_excel_from_view_all','SinhVienController@export_excel_from_view_all')->name('export_excel_from_view_all');
		});
		Route::resource('sinh_vien','SinhVienController');




		Route::resource('lop','LopController');
	});
	Route::group(['as' => 'giua_nam.', 'prefix' => 'giua_nam'],function(){
		// form chuyển lớp hàng loạt sinh viên
		Route::get('view_chuyen_lop','GiuaNamController@view_chuyen_lop')->name('view_chuyen_lop');
		Route::post('process_chuyen_lop','GiuaNamController@process_chuyen_lop')->name('process_chuyen_lop');

		// form nhập file excel thông tin sinh viên
		Route::get('view_cap_nhat_sinh_vien_by_excel','GiuaNamController@view_cap_nhat_sinh_vien_by_excel')->name('view_cap_nhat_sinh_vien_by_excel');
		Route::post('process_cap_nhat_sinh_vien_by_excel','GiuaNamController@process_cap_nhat_sinh_vien_by_excel')->name('process_cap_nhat_sinh_vien_by_excel');
	});
	Route::get('logout','LoginController@logout')->name('logout');
});

Route::get('send_mail','Controller@send_mail');

app/Models/SinhVien.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use DateTime;

class SinhVien extends Model
{
    protected $table = 'sinh_vien';
    protected $fillable = ['ma','ten','ngay_sinh','gioi_tinh','anh','ma_lop'];
    protected $attributes = [
        'anh' => '',
        'gioi_tinh' => '0',
        'ma_lop' => '2',
    ];
    protected $primaryKey = 'ma';

    public $timestamps = false;
    public function lop()
    {
        return $this->belongsTo('App\Models\Lop','ma_lop');
    }

    public function getTuoiAttribute()
    {
		$age = date_diff(date_create($this->ngay_sinh), date_create('now'))->y;
	    return $age;
    }
    public function getTenGioiTinhAttribute()
    {
    	if($this->gioi_tinh==1){
    		return "Nu";
    	}
    	else{
    		return "Nam";
    	}
    }
}

app/Http/Controllers/SinhVienController.php
<?php

namespace App\Http\Controllers;

use App\Models\SinhVien;
use App\Models\Lop;
use Illuminate\Http\Request;
use App\Imports\SinhVienImport;
use Excel;
use Storage;
use App\Exports\SinhVienExport;
use App\Http\Requests\SinhVienRequest;

class SinhVienController extends Controller
{
    protected $table = 'sinh_vien';

    public function index(Request $request)
    {
        $tim_kiem = $request->get('tim_kiem');
        $array_sinh_vien = SinhVien::where('sinh_vien.ten','like',"%$tim_kiem%")
        ->paginate(2);
        return view("$this->table.index",[
            'array_sinh_vien' => $array_sinh_vien,
            'tim_kiem'        => $tim_kiem,
        ]);
    }

    public function create(Request $request)
    {
        $array_lop = Lop::get();

        $ma_lop = $request->get('ma_lop');
        return view("$this->table.create",compact('array_lop','ma_lop'));
    }

    public function store(SinhVienRequest $request)
    {
        SinhVien::create($request->all());
    }

    public function show($ma)
    {
        // $sinh_vien = SinhVien::where('ma',$ma)->first();
        $sinh_vien = SinhVien::find($ma);
        return $sinh_vien->ten;
    }

    public function edit($ma)
    {
        $sinh_vien = SinhVien::find($ma);
        $array_lop = Lop::get();

        return view("$this->table.edit",[
            'sinh_vien' => $sinh_vien,
            'array_lop' => $array_lop,
        ]);
    }

    public function update(Request $request, $ma)
    {
        $sinh_vien = SinhVien::find($ma);
        $sinh_vien->ten = $request->get('ten');
        $sinh_vien->ngay_sinh = $request->get('ngay_sinh');
        $sinh_vien->ma_lop = $request->get('ma_lop');
        $sinh_vien->save();

    }

    public function destroy($ma)
    {
        SinhVien::find($ma)->delete();
    }

    public function choose_by_lop()
    {
        $array_lop = Lop::get();
        return view("$this->table.choose_by_lop",compact('array_lop'));
    }

    public function view_by_lop(Request $rq)
    {
        $ma_lop = $rq->get('ma_lop');

        $array_sinh_vien = SinhVien::where('ma_lop',$ma_lop)->get();

        $array_lop = Lop::get();

        return view("$this->table.view_by_lop",compact('array_sinh_vien','array_lop','ma_lop'));
    }
    public function view_insert_with_excel()
    {
        return view("$this->table.view_insert_with_excel");
    }
    public function process_insert_with_excel(Request $rq)
    {
        Excel::import(new SinhVienImport, $rq->file('excel_sinh_vien')->path());
    }
    public function export_excel_from_view_all()
    {
         return Excel::download(new SinhVienExport, 'sinh_vien_list_all.xlsx');
    }
    public function view_change_anh($ma)
    {
        return view("$this->table.view_change_anh",['ma' => $ma]);
    }
    public function process_change_anh(Request $rq, $ma)
    {
        $file_anh = $rq->file('anh_sinh_vien');

        $ten_file_anh  = time().".".$file_anh->extension();

        Storage::disk('public')->putFileAs("anh_sinh_vien", $file_anh, $ten_file_anh);
        
        SinhVien::find($ma)->update(['anh' => $ten_file_anh]);
    }
    public function form()
    {
        $array_lop = Lop::get();

        return view('sinh_vien.form',compact('array_lop'));
    }
    public function ajax(Request $rq)
    {
        $ma_lop = $rq->get('ma_lop');
        $ten    = $rq->get('ten');
        $array_sinh_vien = SinhVien::where('ma_lop',$ma_lop)
        ->where('ten','like',"%$ten%")
        ->get();

        return $array_sinh_vien;
    }
}

resources/views/sinh_vien/choose_by_lop.blade.php
<form action="{{ route('sinh_vien.view_by_lop') }}">
	Chọn lớp để xem
	<select name="ma_lop">
		@foreach ($array_lop as $lop)
			<option value="{{$lop->ma}}">
				{{$lop->ten}}
			</option>
		@endforeach
	</select>
	<button>OK</button>
</form>

resources/views/sinh_vien/create.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('sinh_vien.store') }}" method="post">
	{{csrf_field()}}
	Ten
	<input type="text" name="ten" value="{{old('ten')}}">
	<br>
	Ngay Sinh
	<input type="date" name="ngay_sinh" value="{{old('ngay_sinh')}}">
	<br>
	Giới tính
	<input type="radio" name="gioi_tinh" value="1">Nam
	<input type="radio" name="gioi_tinh" value="0">Nữ
	<br>
	<input type="" name="">
	Chọn lớp
	<select name="ma_lop">
		@foreach ($array_lop as $lop)
			<option value="{{$lop->ma}}"
			@if ($lop->ma == $ma_lop)
				selected 
			@endif
			>
				{{$lop->ten}}
			</option>
		@endforeach
	</select>
	<br>
	<button>Them</button>
</form>

resources/views/sinh_vien/edit.blade.php
<form action="{{ route('sinh_vien.update',['ma' => $sinh_vien->ma]) }}" method="post">
	<input type="hidden" name="_method" value="PUT">
	{{csrf_field()}}
	Ten
	<input type="text" name="ten" value="{{$sinh_vien->ten}}">
	<br>
	Ngay sinh
	<input type="date" name="ngay_sinh" value="{{$sinh_vien->ngay_sinh}}">
	<br>
	Chọn lớp
	<select name="ma_lop">
		@foreach ($array_lop as $lop)
			<option value="{{$lop->ma}}"
			@if ($lop->ma == $sinh_vien->ma_lop)
				selected 
			@endif
			>
				{{$lop->ten}}
			</option>
		@endforeach
	</select>
	<button>Sua</button>
</form>

resources/views/sinh_vien/form.blade.php
@extends('layout.master')
@push('css')
<link rel="stylesheet" type="text/css" href="{{ asset('css/select2.min.css') }}">
@endpush

@section('content')
<form>
	Chọn lớp
	<select id="select_lop">
		<option disabled selected>
			Hãy chọn lớp
		</option>
		@foreach ($array_lop as $lop)
			<option value="{{$lop->ma}}">
				{{$lop->ten}}
			</option>
		@endforeach
	</select>
	<div>
		Chọn sinh viên
		<select id="select_sinh_vien" style="width: 100px;">
			
		</select>
	</div>	
</form>

@endsection

@push('js')
<script type="text/javascript" src='{{ asset('js/select2.min.js') }}'></script>
<script type="text/javascript">
$(document).ready(function() {
	$("#select_lop").select2();
	$("#select_sinh_vien").select2({
		ajax: {
			url: '{{ route('ajax') }}',
			dataType: 'json',
			type: 'GET',
			data: function (params) {
		      	return {
		        	ten: params.term,
		        	ma_lop: $("#select_lop").val()
		      	};
		    },
		    processResults: function (data) {
			    return {
			        results: $.map(data, function(obj) {
			            return { 
			            	id: obj.ma, 
			            	text: obj.ten 
			            };
			        })
			    };
			},
			placeholder: 'Search for a repository'
		}
	});
});
</script>
@endpush

resources/views/sinh_vien/index.blade.php
<a href="{{ route('sinh_vien.create') }}">
	Thêm
</a>
<br>
<a href="{{ route('sinh_vien.view_insert_with_excel') }}">
	Thêm bằng excel
</a>
<br>
<a href="{{ route('sinh_vien.choose_by_lop') }}">
	Xem theo lop
</a>
<table border="1" width="100%">
	<caption>
		<form>
			Tim kiem theo ten
			<input type="search" name="tim_kiem" value="{{$tim_kiem}}">
		</form>
	</caption>
	<tr>
		<th>Tên</th>
		<th>Tuổi</th>
		<th>Gioi tinh</th>
		<th>Ảnh</th>
		<th>Ten Lop</th>
		<th>Xem</th>
		<th>Sửa</th>
		<th>Xóa</th>
	</tr>
	@foreach ($array_sinh_vien as $sinh_vien)
		<tr>
			<td>
				{{$sinh_vien->ten}}
			</td>
			<td>
				{{$sinh_vien->tuoi}}
			</td>
			<td>
				{{$sinh_vien->ten_gioi_tinh}}
			</td>
			<td>
				<img src="{{asset("uploads/anh_sinh_vien/$sinh_vien->anh")}}" height="200">
				<a href="{{ route('sinh_vien.view_change_anh',['ma' => $sinh_vien->ma]) }}">
					Đổi ảnh
				</a>
			</td>
			<td>
				{{$sinh_vien->lop->ten}}
			</td>
			<td>
				<a href="{{ route('sinh_vien.show',['ma' => $sinh_vien->ma]) }}">
					Xem
				</a>
			</td>
			<td>
				<a href="{{ route('sinh_vien.edit',['ma' => $sinh_vien->ma]) }}">
					Sua
				</a>
			</td>
			<td>
				<form action="{{ route('sinh_vien.destroy',['ma' => $sinh_vien->ma]) }}" method="post">
					{{csrf_field()}}
					<input type="hidden" name="_method" value="DELETE">
					<button>Xoa</button>
				</form>
			</td>
		</tr>
	@endforeach
</table>
{{$array_sinh_vien->appends(['tim_kiem' => $tim_kiem])->links()}}

resources/views/sinh_vien/list_all.blade.php
<table border="1" width="100%">
	<tr>
		<th>Tên</th>
		<th>Tuổi</th>
		<th>Gioi tinh</th>
		<th>Ten Lop</th>
	</tr>
	@foreach ($array_sinh_vien as $sinh_vien)
		<tr>
			<td>
				{{$sinh_vien->ten}}
			</td>
			<td>
				{{$sinh_vien->tuoi}}
			</td>
			<td>
				{{$sinh_vien->ten_gioi_tinh}}
			</td>
			<td>
				{{$sinh_vien->lop->ten}}
			</td>
		</tr>
	@endforeach
</table>

resources/views/sinh_vien/view_by_lop.blade.php
<form action="{{ route('sinh_vien.view_by_lop') }}">
	Chọn lớp để xem
	<select name="ma_lop">
		@foreach ($array_lop as $lop)
			<option value="{{$lop->ma}}" 
			@if ($lop->ma == $ma_lop)
				selected 
			@endif>
				{{$lop->ten}}
			</option>
		@endforeach
	</select>
	<button>OK</button>
</form>
<a href="{{ route('sinh_vien.create',['ma_lop' => $ma_lop]) }}">
	Thêm
</a>
<table border="1" width="100%">
	<tr>
		<th>Tên</th>
		<th>Ngay sinh</th>
		<th>Xem</th>
		<th>Sửa</th>
		<th>Xóa</th>
	</tr>
	@foreach ($array_sinh_vien as $sinh_vien)
		<tr>
			<td>
				{{$sinh_vien->ten}}
			</td>
			<td>
				{{$sinh_vien->ngay_sinh}}
			</td>
			<td>
				<a href="{{ route('sinh_vien.show',['ma' => $sinh_vien->ma]) }}">
					Xem
				</a>
			</td>
			<td>
				<a href="{{ route('sinh_vien.edit',['ma' => $sinh_vien->ma]) }}">
					Sua
				</a>
			</td>
			<td>
				<form action="{{ route('sinh_vien.destroy',['ma' => $sinh_vien->ma]) }}" method="post">
					{{csrf_field()}}
					<input type="hidden" name="_method" value="DELETE">
					<button>Xoa</button>
				</form>
			</td>
		</tr>
	@endforeach
</table>

resources/views/sinh_vien/view_change_anh.blade.php
<form action="{{ route('sinh_vien.process_change_anh',['ma' => $ma]) }}" method="post" enctype="multipart/form-data">
	{{csrf_field()}}
	Chọn file ảnh
	<br>
	<input type="file" name="anh_sinh_vien" accept="image/png, image/jpeg">
	<button>OK</button>
</form>

resources/views/sinh_vien/view_insert_with_excel.blade.php
<form action="{{ route('sinh_vien.process_insert_with_excel') }}" method="post" enctype="multipart/form-data">
	{{csrf_field()}}
	Chọn file excel
	Những cột cần điền(Tên,Ngày Sinh, Giới Tính)
	<br>
	<input type="file" name="excel_sinh_vien" accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel">
	<button>OK</button>
</form>