routes/web.php
<?php

Route::get('doi_ngon_ngu/{ngon_ngu}',function($ngon_ngu){
	Session::put('ngon_ngu',$ngon_ngu);
});

Route::get('test','Controller@test');


Route::get('','LoginController@view_login')->name('view_login');
Route::post('process_login','LoginController@process_login')->name('process_login');

Route::group(['middleware' => 'CheckLogin'],function(){
	Route::get('welcome','Controller@welcome')->name('welcome');

	Route::get('form','SinhVienController@form');
	Route::get('ajax','SinhVienController@ajax')->name('ajax');

	Route::group(['as' => 'dau_nam.', 'prefix' => 'dau_nam'],function(){
		Route::group(['as' => 'sinh_vien.', 'prefix' => 'sinh_vien'],function(){
			Route::get('choose_by_lop','SinhVienController@choose_by_lop')->name('choose_by_lop');
			Route::get('view_by_lop','SinhVienController@view_by_lop')->name('view_by_lop');

			// đổi ảnh
			Route::get('view_change_anh/{ma}','SinhVienController@view_change_anh')->name('view_change_anh');
			Route::post('process_change_anh/{ma}','SinhVienController@process_change_anh')->name('process_change_anh');

			// làm việc với file excel
			Route::get('view_insert_with_excel','SinhVienController@view_insert_with_excel')->name('view_insert_with_excel');
			Route::post('process_insert_with_excel','SinhVienController@process_insert_with_excel')->name('process_insert_with_excel');

			Route::get('export_excel_from_view_all','SinhVienController@export_excel_from_view_all')->name('export_excel_from_view_all');
		});
		Route::resource('sinh_vien','SinhVienController');




		Route::resource('lop','LopController');
	});
	Route::group(['as' => 'giua_nam.', 'prefix' => 'giua_nam'],function(){
		// form chuyển lớp hàng loạt sinh viên
		Route::get('view_chuyen_lop','GiuaNamController@view_chuyen_lop')->name('view_chuyen_lop');
		Route::post('process_chuyen_lop','GiuaNamController@process_chuyen_lop')->name('process_chuyen_lop');

		// form nhập file excel thông tin sinh viên
		Route::get('view_cap_nhat_sinh_vien_by_excel','GiuaNamController@view_cap_nhat_sinh_vien_by_excel')->name('view_cap_nhat_sinh_vien_by_excel');
		Route::post('process_cap_nhat_sinh_vien_by_excel','GiuaNamController@process_cap_nhat_sinh_vien_by_excel')->name('process_cap_nhat_sinh_vien_by_excel');
	});
	Route::get('logout','LoginController@logout')->name('logout');
});

Route::get('send_mail','Controller@send_mail');

app/Http/Controllers/GiuaNamController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\SinhVien;
use App\Models\Lop;
use Excel;
use App\Imports\SinhVienUpdateOrCreateImport;

class GiuaNamController extends Controller
{
    public function view_chuyen_lop()
    {
    	$array_sinh_vien = SinhVien::get();

    	$array_lop = Lop::get();

    	return view('giua_nam.view_chuyen_lop',[
    		'array_sinh_vien' => $array_sinh_vien,
    		'array_lop' => $array_lop,
    	]);
    }
    public function process_chuyen_lop(Request $rq)
    {
    	$array_sinh_vien = $rq->array_sinh_vien;
    	$ma_lop = $rq->ma_lop;

    	// SinhVien::whereIn('ma',$array_sinh_vien);
    	SinhVien::whereIn('ma',$array_sinh_vien)->update([
    		'ma_lop' => $ma_lop
    	]);
    }
    public function view_cap_nhat_sinh_vien_by_excel()
    {
    	return view('giua_nam.view_cap_nhat_sinh_vien_by_excel');
    }
    public function process_cap_nhat_sinh_vien_by_excel(Request $rq)
    {
    	$file = $rq->file('excel_sinh_vien');

    	Excel::import(new SinhVienUpdateOrCreateImport, $file);
    }
}

resources/views/giua_nam/view_cap_nhat_sinh_vien_by_excel.blade.php
<form action="{{ route('giua_nam.process_cap_nhat_sinh_vien_by_excel') }}" method="post" enctype="multipart/form-data">
	{{csrf_field()}}
	Chọn file excel
	Những cột cần điền(Mã, Tên,Ngày Sinh)
	<br>
	<input type="file" name="excel_sinh_vien" accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel">
	<button>OK</button>
</form>

resources/views/giua_nam/view_chuyen_lop.blade.php
@extends('layout.master')
@push('css')
<link rel="stylesheet" type="text/css" href="{{ asset('css/select2.min.css') }}">
@endpush
@section('content')
<form action="{{ route('giua_nam.process_chuyen_lop') }}" method="post">
	{{ csrf_field() }}
	Chọn những sinh viên để chuyển lớp
	<select id="select_sinh_vien" multiple name="array_sinh_vien[]">
		@foreach ($array_sinh_vien as $sinh_vien)
			<option value="{{ $sinh_vien->ma }}">
				{{ $sinh_vien->ten }} ({{ $sinh_vien->ma }})
			</option>
		@endforeach
	</select>
	<br>
	Chọn lớp muốn chuyển tới
	<select id="select_lop" name="ma_lop">
		@foreach ($array_lop as $lop)
			<option value="{{ $lop->ma }}">
				{{ $lop->ten }}
			</option>
		@endforeach
	</select>
	<button>Chuyển lớp</button>
</form>
@endsection

@push('js')
<script type="text/javascript" src='{{ asset('js/select2.min.js') }}'></script>
<script type="text/javascript">
$(document).ready(function() {
	$("#select_sinh_vien").select2();
});
</script>
@endpush